<a href="https://colab.research.google.com/github/sleeptiger/Abc-project/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 라이브러리란?
>- 모듈은 파이썬 확장자로 이루어져 있는 실행 가능한 하나의 파일이다.
>- 모듈안에는 한개 이상 함수, 클래스 변수가 있다.
>- 라이브러리는 `import` 로 호출한다.



In [3]:
import numpy as np # as np = numpy를 np로 사용이 가능하다.

# Numpy란?


## Numpy 
>- 다차원 배열을 쉽고 효율적으로 계산할 수 있도록 해주는 python 라이브러리
<br>
<br>
#### why Numpy
>- 데이터는 이미지, 오디오, 텍스트 등 다양하다.
>- 모든 데이터는 결국, 숫자의 배열 형태로 해석이 가능하다.
>- Numpy는 python에서 모든 데이터를 자료형으로 분석하고 계산하기 위한 라이브러리이다.

## 배열이란?
1. 같은 타입을 가지는 데이터가 나열된 집합
2. 축의 개수에 따라 차원이 달라진다.
<br>
<br>
>- axis0 = 세로/ axis1= 가로/ axis3 = 깊이

In [ ]:
silver = np.array([[1,2,3],
                  [4,5,6]])
np.shape(silver) # 세로로 2줄 가로로 3줄

(2, 3)

In [ ]:
abc = np.array([[[1,2,3],
               [4,5,6]],
               [[7,8,9],
               [10,11,12]]])
np.shape(abc)

(2, 2, 3)

## 배열과 슬라이싱, 정렬
1. 배열생성
    >- 리스트를 np로 변경 
    >- np를 사용해서 생성 -> 타입설정 가능
    >- 파일기반 배열 생성

In [9]:
#리스트를 np로 변경
x = [1,2,3,4]
print(type(x))
np.array(x)

<class 'list'>


array([1, 2, 3, 4])

In [ ]:
#   np.arange(x,y,z)   -- x = 시작 하는 숫자
#                         Y = 끝나는 숫자(Y미만의 숫자)
#                         Z = 간격

In [10]:
np.linspace(0,10,2)   # linspace(x,y,z) - z숫자 만큼 배열 시킨다.

array([ 0., 10.])

In [15]:
# 여러가지 NUMPY 배열 생성기 
np.zeros((3,5))
# axis0 = 3  axis1= 5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.full((3,3),10)
#   axis0 =3 axis1 = 3 채워주는 숫자는 10

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### 슬라이싱
- 특정 구간을 불러 들인다.
- `,` 중심으로 (x,y,z) = (axis0, axis1, axis3) = (행 인덱스, 열 인덱스, N축 인덱스)
-  `:` = 전체를 뜻함 ex) eve[:,1] = 모든 행에 1번 열 인덱스 출력


In [18]:
eve = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [26]:
 np.array(eve[:,1])

array([2, 5, 8])

In [27]:
eve[0,2]

3

#### FANCY 인덱싱
- 리스트로서 특정 행/ 열을 슬라이싱 할 수 있다.

In [36]:
arr=np.zeros((8,8))

In [51]:
arr1 =np.arange(1,17)
arr2 = arr1.reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
arr2[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [78]:
arr2[1::2, [0,2]] # arr2[x:y:z, xz]  = x는 행의 시작점, z는 간격 수/ xz=열 컬럼

array([[ 5,  7],
       [13, 15]])

In [79]:
matrix = np.zeros((8,8))
matrix[::2,[1,3,5,7]] = 1
matrix[1::2,[0,2,4,6]] = 1
np.array(matrix)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### boolearn 인덱싱
- true 값만 출력

In [88]:
arr2>8 # True/False만 출력을 원하면

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
arr2[arr2>8] # True/False값을 토대로 출력

array([ 9, 10, 11, 12, 13, 14, 15, 16])

## 유용한 Numpy  함수

In [ ]:
# np.min() - 최솟값
# np.max() - 최댓값
# np.argmin() -최소 인덱스 값
# np.argmax() - 최대 인덱스 값
# np.sum() - 전체 합
# np.mean() - 평균
# np.where(arr2 == 7) - arr2 에서 7의 위치를 찾는다

#### 배열 차원 변경

In [97]:
abc1 = np.arange(0,16)
abc1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [102]:
abc2 = abc1.reshape(4,-1)
abc2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
abc2_2 = abc1.reshape(4,4)
abc2_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 정렬 함수     

In [106]:
arr = np.array([[11, 9, 11, 12], 
                [8, 9, 5, 7], 
                [3, 1, 2, 4],
                [14, 16, 13, 15]])

In [114]:
np.sort(arr, axis=0) # 위에서 아래로 높은순

array([[ 3,  1,  2,  4],
       [ 8,  9,  5,  7],
       [11,  9, 11, 12],
       [14, 16, 13, 15]])

In [115]:
np.sort(arr, axis=0)[::-1] #위에서 아래로 낮음차순

array([[14, 16, 13, 15],
       [11,  9, 11, 12],
       [ 8,  9,  5,  7],
       [ 3,  1,  2,  4]])

In [116]:
np.sort(arr, axis=1) # 왼쪽에서 오른쪽으로 높은 차순 정력

array([[ 9, 11, 11, 12],
       [ 5,  7,  8,  9],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [117]:
np.sort(arr, axis=1)[::-1] # 행 뒤집고 오름 차순

array([[13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  7,  8,  9],
       [ 9, 11, 11, 12]])